services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: golang:bookworm
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
